- name: Update README
  run: |
    # 替换 README 中的时间标记
    sed -i "s/<!-- LAST_UPDATE -->.*<!-- \/LAST_UPDATE -->/<!-- LAST_UPDATE -->$(date -u +'%Y-%m-%d %H:%M:%S')<!-- \/LAST_UPDATE -->/g" README.md
- name: Commit changes
  uses: stefanzweifel/git-auto-commit-action@v4
  with:
    commit_message: "Update timestamp in README"
