name: Update Timestamp

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # 每天UTC午夜运行

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update timestamp
      run: |
        sed -i "s/{{LAST_UPDATED}}/$(date -u '+%Y-%m-%d %H:%M:%S UTC')/g" README.md
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add README.md
        git commit -m "Update timestamp"
        git push
